# Generated by Django 3.2.4 on 2021-06-06 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('timezone', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=4)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timezone_offset', models.IntegerField()),
                ('dt', models.DateTimeField(null=True)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pressure', models.IntegerField(null=True)),
                ('humidity', models.IntegerField(null=True)),
                ('visibility', models.IntegerField(null=True)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('description', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ('timezone',),
            },
        ),
        migrations.CreateModel(
            name='WeatherByMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(null=True)),
                ('precipitation', models.DecimalField(decimal_places=3, max_digits=5)),
                ('weather_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minutely', to='api.weatherinfo')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherByHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(null=True)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('visibility', models.IntegerField(null=True)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=25)),
                ('weather_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hourly', to='api.weatherinfo')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherByDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(null=True)),
                ('average_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('visibility', models.IntegerField(null=True)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=25)),
                ('weather_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily', to='api.weatherinfo')),
            ],
        ),
    ]
