# Generated by Django 3.2.4 on 2021-06-06 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherbyday',
            old_name='average_temperature',
            new_name='temp',
        ),
    ]
